/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
    "./src/app/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-blue": "#004165",
        "primary-purple": "#4a2c8f",
        "secondary-blue": "#5b9bd5",
        "accent-teal": "#00a0b0",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      boxShadow: {
        soft: "0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03)",
        hover:
          "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
      },
      typography: {
        DEFAULT: {
          css: {
            maxWidth: "65ch",
            color: "var(--dark-gray)",
            h1: {
              color: "var(--primary-blue)",
            },
            h2: {
              color: "var(--primary-blue)",
            },
            h3: {
              color: "var(--primary-blue)",
            },
            a: {
              color: "var(--secondary-blue)",
              "&:hover": {
                color: "var(--primary-blue)",
              },
            },
          },
        },
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/typography")],
  safelist: [
    "bg-blue-900",
    "bg-blue-800",
    "bg-blue-700",
    "bg-blue-600",
    "bg-blue-500",
    "bg-blue-400",
    "bg-blue-300",
    "bg-blue-200",
    "bg-blue-100",
    "bg-blue-50",
    "text-blue-900",
    "text-blue-800",
    "text-blue-700",
    "text-blue-600",
    "text-blue-500",
    "text-blue-400",
    "text-blue-300",
    "text-blue-200",
    "text-blue-100",
    "text-blue-50",
    "bg-purple-900",
    "bg-purple-800",
    "bg-purple-700",
    "bg-purple-600",
    "bg-purple-500",
    "bg-purple-400",
    "bg-purple-300",
    "bg-purple-200",
    "bg-purple-100",
    "bg-purple-50",
    "text-purple-900",
    "text-purple-800",
    "text-purple-700",
    "text-purple-600",
    "text-purple-500",
    "text-purple-400",
    "text-purple-300",
    "text-purple-200",
    "text-purple-100",
    "text-purple-50",
    "bg-green-100",
    "bg-green-500",
    "bg-green-600",
    "text-green-500",
    "text-green-600",
    "bg-yellow-50",
    "bg-yellow-400",
    "text-yellow-400",
    "text-yellow-700",
    "border-yellow-400",
    "border-blue-400",
    "border-blue-500",
    "border-blue-800",
    "hover:bg-blue-50",
    "hover:bg-blue-700",
    "hover:bg-blue-800",
    "hover:bg-gray-50",
    "hover:bg-gray-100",
    "hover:text-blue-900",
    "hover:text-gray-900",
    "hover:text-white",
    "hover:text-indigo-900",
    "hover:border-blue-400",
    "focus:border-blue-500",
    "focus:ring-blue-500",
    "focus:ring-indigo-500",
    "focus:ring-offset-2",
    "focus:outline-none",
    "focus:ring-2",
    "focus:ring-inset",
  ],
};
